<?php

function nodequery2_menu() {
  $items = array();
  $items['nodequery2/form'] = array(
    'title' => t('Node searcher'),
    'page callback' => 'drupal_get_form',
    //'delivery callback' => 'drupal_get_form',
    'menu_name' => 'node search',
    'page arguments' => array('nodequery2_form'),
    'access callback' => TRUE,
    'file' => 'nodequery2.forms.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );
  return $items;
}


function nodequery2_get_last_nodes($query) {


  // = db_query("SELECT title FROM node WHERE (type = '".$type."') AND (title LIKE '%".$query."%')");

  $result = db_query("SELECT nid, title FROM node WHERE title LIKE '%" . $query . "%'");
  $nodes = array();
  foreach ($result as $node) {
    $nodes[$node->nid] = check_plain($node->title);
  }

  return $nodes;
}

/* nodequery2_render_form() {
    $out  = '<div id="nodequery2-form-wrapper">';
    $out .= drupal_get_form('nodequery2_form');
    $out .= '</div>';
    return $out;
}